pcg_0 = csvread("0.csv");
pcg_0_transpose = transpose(pcg_0);
pcg_0_training.wav_data = pcg_0_transpose;
save("pcg_0_training.mat", "pcg_0_training");
pcg_1 = csvread("1.csv");
pcg_1_transpose = transpose(pcg_1);
pcg_1_training.wav_data = pcg_1_transpose;
save("pcg_1_training.mat", "pcg_1_training");
pcg_2 = csvread("2.csv");
pcg_2_transpose = transpose(pcg_2);
pcg_2_training.wav_data = pcg_2_transpose;
save("pcg_2_training.mat", "pcg_2_training");
pcg_3 = csvread("3.csv");
pcg_3_transpose = transpose(pcg_3);
pcg_3_training.wav_data = pcg_3_transpose;
save("pcg_3_training.mat", "pcg_3_training");
pcg_4 = csvread("4.csv");
pcg_4_transpose = transpose(pcg_4);
pcg_4_training.wav_data = pcg_4_transpose;
save("pcg_4_training.mat", "pcg_4_training");
pcg_5 = csvread("5.csv");
pcg_5_transpose = transpose(pcg_5);
pcg_5_training.wav_data = pcg_5_transpose;
save("pcg_5_training.mat", "pcg_5_training");
pcg_6 = csvread("6.csv");
pcg_6_transpose = transpose(pcg_6);
pcg_6_training.wav_data = pcg_6_transpose;
save("pcg_6_training.mat", "pcg_6_training");